### ISSUE TITLE
route的构造有问题

### ISSUE THREAD

**Issue by signhuwei** [maptalks/maptalks.routeplayer#1]
Route extend r就行了吧
要不然按照潜规则如果r设置了lineSymbol,[route的symbol](https://github.com/maptalks/maptalks.routeplayer/blob/gh-pages/index.js#L218)就应该是这样取啊
 symbol : route.route.lineSymbol || this.options['lineSymbol']

并且route的[构造](https://github.com/maptalks/maptalks.routeplayer/blob/gh-pages/index.js#L6)
会导致path重复引用
route.path = [...]
route.route.path = [...]

**Comment by fuzhenn** [comment]
你说的有道理, 可以更简洁优雅一些

不过设计上, route不是直接给用户用的, 而是内部使用的类, 公开给用户会增加使用复杂度

我比较倾向于RoutePlayer上定义方法, 来修改route

**Comment by fuzhenn** [comment]
r不是一个类, 所以是无法`Route extends r`的

我给Route类增加了`markerSymbol`/`lineSymbol`属性, 调用比较方便

另外给player增加了`markerSymbol`/`lineSymbol`的'set'/'get'方法:

具体见commit:

https://github.com/maptalks/maptalks.routeplayer/commit/5f118fba288ef27cd16e529539e84744cdb1a6d7

**Comment by fuzhenn** [comment]
上面增加的方法还没测试过, 你可以先试用, 有问题随时发issue
