### ISSUE TITLE
区分渲染模式

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.routeplayer#20]
### canvas模式
即现在基于VectorLayer的实现

### gl模式(默认模式)
基于GLTFLayer + PointLayer + LineStringLayer的实现。
轨迹marker既可以是GLTF模型，也可以是普通marker，可以在设置中指定。
gl模式允许从外部传一个GroupGLLayer到player中，把PointLayer/GLTFLayer + LineStringLayer添加到GroupGLLayer中

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.routeplayer/pull/46
