### ISSUE TITLE
routeplayer相关api

### ISSUE THREAD

**Issue by binfenshijie** [maptalks/maptalks.routeplayer#3]
var route = [
    {
        "path" : [
            [121.475031060928,31.2611187865471,301000],
            [121.47940842604,31.263466566376,541000]
        ]
    }
];
经纬度后面这个数据是什么意思，经试验应该是跟速度有关
另外，线的样式和图标是否可配置

**Comment by binfenshijie** [comment]
欧，我看到在插件的js中可以配置marker和line,symbol样式了,但是lon,lat后面这个参数怎么设置呢

**Comment by fuzhenn** [comment]
那个是当前位置，距离开始的时间（毫秒为单位）

**Comment by binfenshijie** [comment]
棒棒哒
