### ISSUE TITLE
rotationX和rotationZ的角度只能适用于经纬度坐标系

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.routeplayer#50]
目前rotationX和rotationZ的计算逻辑只适用于球面经纬度坐标系，但无法适用于平面坐标系（例如traverse_mercator，identity等）

可以考虑在options中增加坐标系是否是cartesian坐标系的设置参数。

**Comment by deyihu** [comment]
@fuzhenn need new version by https://github.com/maptalks/maptalks.routeplayer/commit/3a696922546aab54b9071608b79df3b074c9006d
